# Generated by Django 5.1.3 on 2024-11-27 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('organizer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('contact_person_name', models.CharField(max_length=100)),
                ('contact_person_email', models.EmailField(max_length=254, unique=True)),
                ('contact_person_phone', models.CharField(max_length=15, unique=True)),
                ('organizer_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=6, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('birth_date', models.DateField()),
                ('department', models.CharField(max_length=200)),
                ('participant_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('faculty', 'Faculty')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('expected_participants', models.PositiveIntegerField()),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='bookings.organizer')),
            ],
            options={
                'unique_together': {('name', 'date', 'organizer')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.activity')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.participant')),
            ],
            options={
                'unique_together': {('participant', 'activity')},
            },
        ),
    ]
